'use client'

export function LandingPage({ onEnter }: { onEnter: () => void }) {
  return (
    <main className="landing-shell">
      <nav className="landing-nav"><div className="brand"><span className="brand-mark">C</span><span>CarbonCredit<span className="brand-accent">NG</span></span></div><div className="landing-links"><a href="#how-it-works">How it works</a><a href="#impact">Our impact</a><a href="#trust">Trust & verification</a></div><button className="landing-login" onClick={onEnter}>Open platform <span>→</span></button></nav>
      <section className="landing-hero"><div className="landing-copy"><p className="eyebrow">CARBON CREDIT NETWORK <span className="live-dot" /> BUILT ON BOT CHAIN</p><h1>Fund restoration.<br /><em>Prove the impact.</em></h1><p className="landing-lead">CarbonCreditNG connects verified climate projects with organizations ready to make measurable, transparent change across Nigeria and beyond.</p><div className="landing-actions"><button className="primary-cta" onClick={onEnter}>Explore the marketplace <span>↗</span></button><a className="secondary-cta" href="#how-it-works">See how it works <span>↓</span></a></div><div className="landing-proof"><div><strong>19,110 t</strong><span>Verified tonnes</span></div><div><strong>28</strong><span>Active projects</span></div><div><strong>100%</strong><span>On-chain records</span></div></div></div><div className="landing-visual" aria-label="Illustration of a verified forest project"><div className="visual-glow" /><div className="visual-ring ring-a" /><div className="visual-ring ring-b" /><div className="visual-land"><span className="tree tree-a">♧</span><span className="tree tree-b">♧</span><span className="tree tree-c">♧</span><span className="visual-stamp">VERIFIED<br />IMPACT</span></div><div className="visual-card"><span className="verified-chip">● Verified project</span><strong>Ogun Forest Corridor</strong><small>8,450 tCO₂e · Ogun State</small></div></div></section>
      <section className="landing-section" id="how-it-works"><p className="eyebrow">A CLEARER CLIMATE MARKET</p><h2>From evidence to impact,<br /><em>without the guesswork.</em></h2><div className="steps"><article><span>01</span><h3>Projects submit evidence</h3><p>NGOs register restoration work with geospatial evidence, monitoring reports, and community outcomes.</p></article><article><span>02</span><h3>Independent verification</h3><p>Approved verifiers review each claim before credits are issued against the project record.</p></article><article><span>03</span><h3>Companies retire with proof</h3><p>Buy and retire credits, then share a permanent certificate tied to the on-chain retirement.</p></article></div></section>
      <section className="landing-trust" id="trust"><div><p className="eyebrow">DESIGNED FOR ACCOUNTABILITY</p><h2>Every tonne has a story.</h2><p>Evidence is anchored to IPFS. Project issuance, marketplace transfers, and retirements are recorded on BOT Chain for anyone to verify.</p></div><div className="trust-points"><div><strong>IPFS</strong><span>Evidence registry</span></div><div><strong>BOT</strong><span>Chain settlement</span></div><div><strong>NFT</strong><span>Retirement certificates</span></div></div></section>
      <footer className="landing-footer"><span>CarbonCredit<span className="brand-accent">NG</span></span><span>Verified climate finance for Nigeria</span><button onClick={onEnter}>Open the platform →</button></footer>
    </main>
  )
}
